name: GHAS Security Pipeline
 
on:
  push:
    branches:
      - main
  pull_request:
 
permissions:
  contents: read
  security-events: write  # Required for security alerts
  actions: read
  id-token: write
 
jobs:
  security-checks:
    name: Run Security Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      # Run CodeQL Analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, python  # Modify based on your project
 
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
 
      - name: Save CodeQL Report
        run: |
          echo "### CodeQL Analysis Report ###" > security-report.log
          cat ./.github/codeql-results.sarif >> security-report.log || echo "No CodeQL results found." >> security-report.log
 
      # Secret Scanning
      - name: Run Secret Scanning
        run: |
          echo "\n### Secret Scanning Report ###" >> security-report.log
          echo "Secret scanning is automatically handled by GitHub." >> security-report.log
 
      # Dependabot Check
      - name: Run Dependabot Security Check
        run: |
          echo "\n### Dependabot Security Report ###" >> security-report.log
          echo "Dependabot checks for dependency vulnerabilities automatically." >> security-report.log
 
      # Upload Final Security Report
      - name: Upload Consolidated Security Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-report.log
